QRSCS/QRSCS/Controllers/IDDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QRSCS.Controllers
{
    public class IDDController : Controller
    {
        // GET: IDD
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IEP()
        {
            return View();
        }
        public ActionResult ViewAllIEP()
        {
            return View();
        }
    }
}

QRSCS/QRSCS/Controllers/UpdateSectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QRSCS.Models;
using QRSCS.Manager;
using System.IO;

namespace QRSCS.Controllers
{

    public class UpdateSectionController : Controller
    {
        [Authorize(Roles = "Admin")]
        public ActionResult AllStudentView()
        {
            NewAdmissionManager obj = new NewAdmissionManager();
            List<NewAdmissionModel> AllStudentView = obj.selectAllAdmission();
            return View(AllStudentView);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult HIView()
        {
            NewAdmissionManager obj = new NewAdmissionManager();
            List<NewAdmissionModel> HIStudentView = obj.selectHI();
            return View(HIStudentView);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult VIView()
        {
            NewAdmissionManager obj = new NewAdmissionManager();
            List<NewAdmissionModel> VIStudentView = obj.selectVI();
            return View(VIStudentView);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult IDDView()
        {
            NewAdmissionManager obj = new NewAdmissionManager();
            List<NewAdmissionModel> IDDStudentView = obj.selectIDD();
            return View(IDDStudentView);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult UpdateStudentView(int GR_NO)
        {
            NewAdmissionManager obj = new NewAdmissionManager();
            NewAdmissionModel user = obj.GetStudent(GR_NO);
            if (user == null)
            {
                TempData["Message"] = "Data not Found";
                return RedirectToAction("AllStudentView");
            }

            else
            {
                return View(user);
            }
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult UpdateStudentView(NewAdmissionModel user)
        {
            if (ModelState.IsValid)
            {

                NewAdmissionManager obj = new NewAdmissionManager();
                user.Updated_By = Convert.ToString(Session["User_ID"]);
                user.Update_Date = DateTime.Now;
                bool check = obj.UpdateStudent(user);
                if (check)
                {
                    TempData["Message"] = "Data Update Successully";
                    return RedirectToAction("AllStudentView");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                TempData["Message"] = "Data Not Updated";
                return View();
            }
        }
    }

}

QRSCS/QRSCS/Views/UpdateSection/AllStudentView.cshtml
@model List<QRSCS.Models.NewAdmissionModel>
@{
    ViewBag.Title = "All Student View";

}

<link href="~/Content/ViewAllUserAssets/css/sb-admin-2.css" rel="stylesheet" />
<link href="~/Content/CreateUser/css/createuser.css" rel="stylesheet" />
<link href="~/Content/ViewAllUserAssets/css/ToggleSwitch.css" rel="stylesheet" />
<main>
    <div class="container-fluid">
         

        <div class="row">
            <!-- Your Profile Views Chart -->
            <div class="col-lg-12 m-b30">
                <div class="widget-box">
                    <div class="wc-title">
                        <h4 id="header">List of All Students</h4>
                    </div>
                    <div class="buttons">
                        <div style="display: inline-block">
                            <button style="width:180px" class="backBtn " id="download-csv" onclick="htmlToCSV()">Export To CSV</button>
                        </div> 
                       <div style="display: inline-block">
                           <button style="width:180px"  class="backBtn " id="download-pdf" onclick="htmlToPDF()">Export To PDF</button>
                       </div>
                       <div style="display: inline-block">
                           <button style="width:150px" class="backBtn " id="print-table" onclick="printTable()">Print Table</button>
                       </div>
                       
                    </div>
                        
                   
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr class="text-center">
                                            <th>GR NO.</th>
                                            <th>Student Name</th>
                                            <th>Father Name</th>
                                            <th>Gender</th>
                                            <th>Disabilty</th>
                                            <th>Modify</th>
                                            <th>Withdraw</th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr class="text-center">
                                                <td>@item.Gr_No</td>
                                                <td>@item.Student_First_Name @item.Student_Last_Name</td>
                                                <td>@item.Father_Name</td>
                                                <td>@item.Gender</td>
                                                <td>@item.Disability</td>
                                                <td>
                                                    @Html.ActionLink("Admission Form", "UpdateStudentView", "UpdateSection", new { GR_NO = @item.Gr_No }, new { @class = "backBtn ",@style="margin-top:0px" })
                                                    @Html.ActionLink("Case History", "CaseHistory", "Editor", new { GR_NO = @item.Gr_No }, new { @class = "backBtn ", @style = "margin-bottom:0px" })
                                                </td>
                                                <td>

                                                    @{
                                                        var stat = string.Empty;
                                                        if (@item.IsActive == true)
                                                        {
                                                            stat = "checked";
                                                        }
                                                        else
                                                        {
                                                            stat = "";
                                                        }
                                                        <label class="switch">
                                                            <input type="checkbox" id="switchId-@item.Gr_No" onchange="UpdateStatus(this,  @item.Gr_No)" @stat>
                                                            <span class="slider round"></span>
                                                        </label>
                                                    }
                                                </td>
                                            </tr>
                                        }


                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Your Profile Views Chart END-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<div class="ttr-overlay"></div>




<script>
    function UpdateStatus(data, userId) {
        var id = data.id;
        var status = document.getElementById(id).checked

        jQuery_3_6_1.post("/Admin/UpdateStudentStatus",
            {
                Status: status,
                UserId: userId
            },
            function (data) {
                if (data == true) {

                }
                else {
                    document.getElementById(id).checked = status;
                    alert("Error Updating")
                }
                console.log(status)
            });
    }
</script>

QRSCS/QRSCS/Views/UpdateSection/HIView.cshtml
@model List<QRSCS.Models.NewAdmissionModel>
@{
    ViewBag.Title = "Hearing Impaired View";
 
}
<link href="~/Content/CreateUser/css/createuser.css" rel="stylesheet" />
<link href="~/Content/ViewAllUserAssets/css/sb-admin-2.css" rel="stylesheet" />

<main>
    <div class="container-fluid">
         

        <div class="row">
            <!-- Your Profile Views Chart -->
            <div class="col-lg-12 m-b30">
                <div class="widget-box">
                    <div class="wc-title">
                        <h4 id="header">List of Hearing Impaired Students</h4>
                    </div>
                    <div class="buttons">
                        <div style="display: inline-block">
                            <button style="width:180px" class="backBtn " id="download-csv" onclick="htmlToCSV()">Export To CSV</button>
                        </div>
                        <div style="display: inline-block">
                            <button style="width:180px" class="backBtn " id="download-pdf" onclick="htmlToPDF()">Export To PDF</button>
                        </div>
                        <div style="display: inline-block">
                            <button style="width:150px" class="backBtn " id="print-table" onclick="printTable()">Print Table</button>
                        </div>

                    </div>
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr class="text-center">
                                            <th>GR NO.</th>
                                            <th>Student Name</th>
                                            <th>Gender</th>
                                            <th>Father Name</th>
                                            <th>Contact Number</th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr class="text-center">
                                                <td>@item.Gr_No</td>
                                                <td>@item.Student_First_Name @item.Student_Last_Name</td>
                                                <td>@item.Father_Name</td>
                                                <td>@item.Gender</td>
                                                <td>@item.Contact</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Your Profile Views Chart END-->
                    </div>
                </div>
            </div>
        </div>
    </div>




</main>

QRSCS/QRSCS/Views/UpdateSection/IDDView.cshtml
@model List<QRSCS.Models.NewAdmissionModel>
@{
    ViewBag.Title = "Intellectual and Developmental Disabilities View";

}
<link href="~/Content/CreateUser/css/createuser.css" rel="stylesheet" />
<link href="~/Content/ViewAllUserAssets/css/sb-admin-2.css" rel="stylesheet" />

 <main>
     <div class="container-fluid">
 

         <div class="row">
             <!-- Your Profile Views Chart -->
             <div class="col-lg-12 m-b30">
                 <div class="widget-box">
                     <div class="wc-title">
                         <h4 id="header">List of Intellectual and Developmental Disabilities Students</h4>
                     </div>
                     <div class="buttons">
                         <div style="display: inline-block">
                             <button style="width:180px" class="backBtn " id="download-csv" onclick="htmlToCSV()">Export To CSV</button>
                         </div>
                         <div style="display: inline-block">
                             <button style="width:180px" class="backBtn " id="download-pdf" onclick="htmlToPDF()">Export To PDF</button>
                         </div>
                         <div style="display: inline-block">
                             <button style="width:150px" class="backBtn " id="print-table" onclick="printTable()">Print Table</button>
                         </div>

                     </div>
                     <div class="card shadow mb-4">
                         <div class="card-body">
                             <div class="table-responsive">
                                 <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                     <thead>
                                         <tr class="text-center">
                                             <th>GR NO.</th>
                                             <th>Student Name</th>
                                             <th>Gender</th>
                                             <th>Father Name</th>
                                             <th>Contact Number</th>

                                         </tr>
                                     </thead>

                                     <tbody>
                                         @foreach (var item in Model)
                                         {
                                             <tr class="text-center">
                                                 <td>@item.Gr_No</td>
                                                 <td>@item.Student_First_Name @item.Student_Last_Name</td>
                                                 <td>@item.Father_Name</td>
                                                 <td>@item.Gender</td>
                                                 <td>@item.Contact</td>
                                             </tr>
                                         }
                                     </tbody>
                                 </table>
                             </div>
                         </div>
                         <!-- Your Profile Views Chart END-->
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </main>

QRSCS/QRSCS/Views/UpdateSection/VIView.cshtml
@model List<QRSCS.Models.NewAdmissionModel>
@{
    ViewBag.Title = "List of Visually Impaired Students";

}
<link href="~/Content/CreateUser/css/createuser.css" rel="stylesheet" />
<link href="~/Content/ViewAllUserAssets/css/sb-admin-2.css" rel="stylesheet" />
<main>
    <div class="container-fluid">
         

        <div class="row">
            <!-- Your Profile Views Chart -->
            <div class="col-lg-12 m-b30">
                <div class="widget-box">
                    <div class="wc-title">
                        <h4 id="header">List of Visually Impaired Students</h4>
                    </div>
                    <div class="buttons">
                        <div style="display: inline-block">
                            <button style="width:180px" class="backBtn " id="download-csv" onclick="htmlToCSV()">Export To CSV</button>
                        </div>
                        <div style="display: inline-block">
                            <button style="width:180px" class="backBtn " id="download-pdf" onclick="htmlToPDF()">Export To PDF</button>
                        </div>
                        <div style="display: inline-block">
                            <button style="width:150px" class="backBtn " id="print-table" onclick="printTable()">Print Table</button>
                        </div>

                    </div>
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr class="text-center">
                                            <th>GR NO.</th>
                                            <th>Student Name</th>
                                            <th>Gender</th>
                                            <th>Father Name</th>
                                            <th>Contact Number</th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr class="text-center">
                                                <td>@item.Gr_No</td>
                                                <td>@item.Student_First_Name @item.Student_Last_Name</td>
                                                <td>@item.Father_Name</td>
                                                <td>@item.Gender</td>
                                                <td>@item.Contact</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- Your Profile Views Chart END-->
                    </div>
                </div>
            </div>
        </div>
    </div>


</main>