QRSCS/QRSCS/Models/Audiology_Assessment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audiology_Assessment
    {
        public int Audiology_Assessment_ID { get; set; }
        public int GR_NO { get; set; }
        public System.DateTime Date_of_Assessment { get; set; }
        public string Left_Ear_Air_UnmaskedFrequency { get; set; }
        public string Left_Ear_Air_Unmasked_HearingLevel { get; set; }
        public string Left_Ear_Bone_MaskedFrequency { get; set; }
        public string Left_Ear_Bone_Masked_HearingLevel { get; set; }
        public string Right_Ear_Air_UnmaskedFrequency { get; set; }
        public string Right_Ear_Air_Unmasked_HearingLevel { get; set; }
        public string Right_Ear_Bone_MaskedFrequency { get; set; }
        public string Right_Ear_Bone_Masked_HearingLevel { get; set; }
        public string Left_Ear_Mean { get; set; }
        public string Right_Ear_Mean { get; set; }
    
        public virtual New_Admission New_Admission { get; set; }
    }
}

QRSCS/QRSCS/Models/Case_History.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case_History()
        {
            this.Behavioral_Observation = new HashSet<Behavioral_Observation>();
            this.Conclusions = new HashSet<Conclusion>();
            this.Development_History = new HashSet<Development_History>();
            this.Education_History = new HashSet<Education_History>();
            this.Family_History = new HashSet<Family_History>();
            this.Medical_History = new HashSet<Medical_History>();
            this.Particulars_of_Sibling = new HashSet<Particulars_of_Sibling>();
            this.Post_Natal = new HashSet<Post_Natal>();
            this.Psycho_Social_Factors = new HashSet<Psycho_Social_Factors>();
            this.Recommendations = new HashSet<Recommendation>();
        }
    
        public int CaseHistory_ID { get; set; }
        public int GR_NO { get; set; }
        public System.DateTime Date_of_Examination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Behavioral_Observation> Behavioral_Observation { get; set; }
        public virtual New_Admission New_Admission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conclusion> Conclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Development_History> Development_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education_History> Education_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family_History> Family_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_History> Medical_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Particulars_of_Sibling> Particulars_of_Sibling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Natal> Post_Natal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Psycho_Social_Factors> Psycho_Social_Factors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recommendation> Recommendations { get; set; }
    }
}

QRSCS/QRSCS/Models/Speech_Therapy_Assessment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech_Therapy_Assessment
    {
        public int Speech_Therapy_Assessment_ID { get; set; }
        public int GR_NO { get; set; }
        public string Speech_Test_Image { get; set; }
        public System.DateTime Date { get; set; }
        public int Std_Class { get; set; }
        public string Full_Name { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual New_Admission New_Admission { get; set; }
    }
}

QRSCS/QRSCS/Controllers/EditorController.cs
using QRSCS.Manager;
using QRSCS.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.ML;
using Microsoft.ML.Transforms.TimeSeries;
using Newtonsoft.Json;
using System.Runtime.InteropServices.ComTypes;
using System.Xml.Linq;

namespace QRSCS.Controllers
{
    public class EditorController : Controller
    {
        // GET: Editor
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult NewAdmission()
        {
            ViewBag.Message = "";
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult NewAdmission(NewAdmissionModel student)
        {
            if (ModelState.IsValid)
            {
                NewAdmissionManager obj = new NewAdmissionManager();
                student.User_ID = Convert.ToInt32(Session["User_ID"]);
                int grno = obj.AddStudent(student);
                if (grno > 0)
                {
                    TempData["Message"] = "Student Added Successfuly and Student GR-NO is " + grno;
                    return RedirectToAction( "Index","Admin");
                }

                else
                {
                    TempData["Message"] = "Student Not Added !";
                }
            }
            else
            {
                TempData["Message"] = "Student Not Added !";
            }
            return View();
        }

        [HttpGet]
        public ActionResult CaseHistory()
        {
            ViewBag.Message = "";
            return View();
        }

        [HttpPost]
        public ActionResult CaseHistory(CaseHistoryModelDTO student)
        {
            if (ModelState.IsValid)
            {
                CaseHistoryManager obj = new CaseHistoryManager();
                int chistoryID = obj.AddCaseHistory(student);
                if (chistoryID > 0)
                {
                    TempData["Message"] = "Student Case History Added Successfuly  " + chistoryID;
                }

                else
                {
                    TempData["Message"] = "Student Case History Not Added !";
                }
            }
            else
            {
                TempData["Message"] = "Student Case History Not Added !";
            }
            return View();
        }

        [HttpGet]
        public ActionResult SpeechTherapyAssessment()

        {
            return View();
        }
        [HttpPost]
        public ActionResult SpeechTherapyAssessment(SpeechTherapyAssessmentModel student )

        {
            if (ModelState.IsValid)
            {
                if (student.Speech_Test_Image_File == null)
                {
                    TempData["Message"] = "Upload User Picture !";
                    return View();
                }
                else
                {
                    string Filename = Path.GetFileNameWithoutExtension(student.Speech_Test_Image_File.FileName);
                    string Extension = Path.GetExtension(student.Speech_Test_Image_File.FileName);
                    Filename = Filename + DateTime.Now.ToString("yymmssfff") + Extension;
                    student.Speech_Test_Image = "~/ProjectData/" + Filename;
                    Filename = Path.Combine(Server.MapPath("~/ProjectData/"), Filename);
                    student.Speech_Test_Image_File.SaveAs(Filename);

                    SpeechTherapyAssessmentManager obj = new SpeechTherapyAssessmentManager();

                    int staid = obj.AddSpeechTherapyAssessment(student);

                        TempData["Success"] = "Success";
                        TempData["Message"] = "Successfully Saved";
                        return View();
                  
                }
            }

            return RedirectToAction("Index","Admin");
        }
        public ActionResult SpeechCaseHistory()
        {
            return View();
        }
                                  
        public  string CSV_FILE_FOR_STA(int uid)
        {
            SpeechTherapyAssessmentModel User = null;
            using (New_QRSCS_DatabaseEntities db = new New_QRSCS_DatabaseEntities())
            {
                var result = db.Speech_Therapy_Assessment.FirstOrDefault(x => x.GR_NO == uid);
                if (result != null)
                {
                    string fileName = AppDomain.CurrentDomain.BaseDirectory + @"Content\CSV_for_AI_Model\" + result.Full_Name.ToLower() + " speech therapy assessment.csv";

                    try
                    {
                        if (System.IO.File.Exists(fileName))
                        {
                            System.IO.File.Delete(fileName);
                        }
                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            var request = db.Speech_Therapy_Assessment.Where(x => x.GR_NO == uid).Select(x => x.Marks).ToList();
                            var request1 = db.Speech_Therapy_Assessment.Where(x => x.GR_NO == uid).Select(x => x.Date).ToList();
                            StringBuilder sb = new StringBuilder();
                            for (int i = 0; i < request.Count; i++)
                            {
                                sb.Append(request1[i] + "," + request[i] + ",");
                                sb.Append("\r\n");

                            }
                            byte[] bytes = Encoding.ASCII.GetBytes(sb.ToString());
                            fs.Write(bytes, 0, bytes.Length);
                        }
                         

                        return "Successful";
                    }
                    catch (Exception Ex)
                    {
                        Console.WriteLine(Ex.ToString());
                    }
                    return "failed";   
                }
                else
                {
                    TempData["Message"] = "No Records Found";
                    Debug.WriteLine(TempData["Message"]);
                    return "UnSuccessful";
                }



            }
        }
        public ActionResult AudiologyAssessment()
        {
            return View();
        }
        public ActionResult Predict_Marks()
        {
            return View();
        }

        public string exec(int uid)
        {

            SpeechTherapyAssessmentModel User = null;
            using (New_QRSCS_DatabaseEntities db = new New_QRSCS_DatabaseEntities())
            {
                var result = db.Speech_Therapy_Assessment.FirstOrDefault(x => x.GR_NO == uid);

                Speech_Therapy_AI_Model model = new Speech_Therapy_AI_Model();
                bool outp = model.exec_model(result.Full_Name.ToLower(), uid);
                if (outp)
                {
                    return "success";
                }
                else
                {
                    return "unsuccesfull";
                }

            }
        }

        public ActionResult Prediction_CSV_to(int uid)
        {
            New_QRSCS_DatabaseEntities db = new New_QRSCS_DatabaseEntities();
            var result = db.Speech_Therapy_Assessment.FirstOrDefault(x => x.GR_NO == uid);
            var csv = new List<STP_data>();
            var lines = System.IO.File.ReadAllLines(AppDomain.CurrentDomain.BaseDirectory + @"Content\CSV_for_AI_Model\" +  result.Full_Name.ToLower() + " speech therapy assessment.csv");
            foreach (var line in lines)
            {
                csv.Add(new STP_data
                {
                    Date = DateTime.Parse(line.Split(',')[0]),
                    Marks = float.Parse(line.Split(',')[1])
                });
            }
            string value = string.Empty;
            value = JsonConvert.SerializeObject(csv, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
            });
            string json = JsonConvert.SerializeObject(csv);

            return Json(value, JsonRequestBehavior.AllowGet);
        }

    }
}

QRSCS/QRSCS/Views/Editor/AudiologyAssessment.cshtml
@{
    ViewBag.Title = "AudiologyAssessment";
}
<link href="~/Content/CreateUser/css/createuser.css" rel="stylesheet" />

<link href="~/Content/ViewAllUserAssets/css/sb-admin-2.css" rel="stylesheet" />


<main>
    <div class="container">
        <header>Audiology Assessment</header>
        <form style="min-height:150px" onsubmit="getstudent();return false">
            <div class="form first">
                <div class="details personal">
                    <div class="fields">
                        <div class="input-field">

                            <input id="_gr_no" type="text" placeholder="Enter Student GR No." required />

                        </div>
                        <div class="input-field">
                            <button type="submit" class="backBtn">
                                <span class="btnText">Submit</span>
                                <i style="transform:none !important" class="uil uil-navigator"></i>
                            </button>



                        </div>
                        <div class="input-field" style="visibility:hidden">

                            <label>Full Name</label>
                            <input type="text" placeholder="Enter Student GR No." />


                        </div>

                        <div class="input-field" style="visibility:hidden">
                            <label>Full Name</label>
                            <input type="text" placeholder="Enter Student GR No." />

                        </div>

                    </div>


                </div>

            </div>
        </form>

        <div id="tabless" class="container-fluid" style="visibility:hidden">

            <div class="row">

                <div class="col-lg-12 m-b30">
                    <div class="widget-box">

                        <div class="card shadow mb-4">

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr class="text-center">
                                                <th>ID</th>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Father Name</th>
                                                <th>Gender</th>
                                                <th>Disability</th>

                                            </tr>
                                        </thead>

                                        <tbody id="SetStudentData"></tbody>
                                    </table>
                                </div>

                            </div>
                            @*    Your Profile Views Chart END*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 mb-4">
                <div class="card shadow p-3 mb-5 bg-white rounded">


                    <div class="card-body">
                        <h5 class="card-title">Left Ear</h5>
                        <center><b>Air Unmasked</b></center>
                        <lable>Frequency (Hz):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5" style="border"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>

                            </tr>
                        </table>
                        <lable>Hearing Level (dBHL):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>

                            </tr>
                        </table>
                        <center><b>Bone Masked</b></center>
                        <lable>Frequency (Hz):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>

                            </tr>
                        </table>
                        <lable>Hearing Level (dBHL):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>

                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card shadow p-3 mb-5 bg-white rounded">


                    <div class="card-body ">
                        <h5 class="card-title">Right Ear</h5>
                        <center><b>Air Unmasked</b></center>
                        <lable>Frequency (Hz):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>

                            </tr>
                        </table>
                        <lable>Hearing Level (dBHL):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                        <center><b>Bone Masked</b></center>
                        <lable>Frequency (Hz):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                        <lable>Hearing Level (dBHL):</lable>
                        <table class="table table-borderless">
                            <tr>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td><input type="text" id="fname" name="fname" size="5"></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <center>
            <div class="input-field">
                <button type="submit" class="backBtn">
                    <span class="btnText">Save and plot</span>
               
                </button>



            </div>
        </center>
    </div>

        <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
</main>

QRSCS/QRSCS/Views/Editor/SpeechTherapyAssessment.cshtml
@model QRSCS.Models.SpeechTherapyAssessmentModel
@{
    ViewBag.Title = "SpeechTherapyAssessment";
 
}
<link href="~/Content/CreateUser/css/createuser.css" rel="stylesheet" />
<main>
    <div class="container">
        <header>Speech Therapy Assessment Form</header>
        @using (Html.BeginForm("SpeechTherapyAssessment", "Editor", FormMethod.Post, new { @id = "formmm", enctype = "multipart/form-data" }))
        {
            <div class="form first">
                <div class="details personal">
                    <span class="title">Personal Details</span>

                    <div class="fields">
                        <div class="input-field">
                            <label>GR No.</label>
                            @Html.TextBoxFor(x => x.GR_NO, new { placeholder = "Enter GR Number", id = "gr_", @required = "required", onchange = "GetInfo(document.getElementById('gr_').value)" })
                        </div>

                        <div class="input-field">
                            <label>Student Full Name</label>
                            @Html.TextBoxFor(x => x.Full_Name, new { placeholder = "Enter Full Name", id = "full_", @required = "required", @readonly = "readonly" })
                        </div>

                        <div class="input-field">
                            <label>Student Class</label>
                            @Html.TextBoxFor(x => x.Std_Class, new { placeholder = "Enter Student Class", id = "class_", @required = "required",@readonly = "readonly" })

                        </div>
                         
                        <div class="input-field">
                            <label>Date of Assesment</label>
                            @Html.TextBoxFor(x => x.Date_of_Assessment, null, new { @type = "date", placeholder = "Enter the Date" , @required = "required" })

                        </div>
                        <div class="input-field">
                            <label>Student Marks Obtained</label>
                            @Html.TextBoxFor(x => x.Marks, null, new { placeholder = "Enter Student Marks", @required = "required" })




                        </div>
                        <div class="input-field">
                            <label>Upload Assesment Image</label>
                            @Html.TextBoxFor(m => m.Speech_Test_Image_File, new { @id = "user-image", @class = "upload-box", type = "file", accept = "image/png, image/jpeg", @required = "required" })
                        </div>

                        <div class="input-field">
                            <label style="visibility:hidden">Upload User Image</label>

                            <div id="preview" style="visibility:hidden;margin:0px;" onclick="preview_modal()" class="backBtn">Preview Image</div>
                        </div>

                        <div class="input-field" style="visibility:hidden">
                            <label>Upload User Image</label>

                        </div>



                    </div>
                </div>

                 


                     

                <div class="buttons">

                    <button type="submit" class=" backBtn"  >
                        <span class="btnText">Submit</span>
                        <i style="transform:none !important" class="uil uil-navigator"></i>
                    </button>
                </div>
                
            </div>

 
        }


    </div>

    <div id="image-preview" class="popup">
        <header>
            <span>Preview of Image</span>
            <div><i onclick="img_modal_close()" class="uil uil-times"></i></div>
        </header>
        <div class="content">
            <center>
                <img width="200px" height="200px" src="" alt="" id="photo-preview" />
            </center>

        </div>
    </div>


</main>



<script src="~/Content/adminassets/assets/js/jquery.min.js"></script>
<script type="text/javascript">
    function GetInfo(id) {
        console.log(id);
        jQuery_3_6_1.get("/Result/GetInfo?GRNO=" + id, function (response) {
            console.log(response);
            jQuery_3_6_1("#full_").val(response.Name + " " + response.Father_Name);
            jQuery_3_6_1("#class_").val(response.Class);
            //document.getElementById("full_").innerHTML = response.Name;
            //document.getElementById("class_").innerHTML = response.Father_Name;


        });
    }
    function GetInfopost() {
        var img = jQuery_3_6_1('#BrowseImage')[0].files[0];
        console.log(img);
        var Db = new FormData();
        //alert($("#gr_").val() + $("#full_").val() + $("#marks").val() + $("#class_").val());
        Db.append("GR_NO", jQuery_3_6_1("#gr_").val());
        Db.append("ImageFile", img);
        var a = jQuery_3_6_1("#datee").val();
        var ab = a.split("T");

        Db.append("Full_Name", $("#full_").val());
        Db.append("Date_of_Assessment", ab[0]);
        Db.append("Marks", $("#marks").val());
        Db.append("std_class", $("#class_").val());
        $.ajax({
            url: 'SpeechTherapyAssessment/Editor',
            type: "Post",

            data: Db,
            contentType: false,
            processData: false,
            enctype: 'multipart/form-data',
            cache: false,
            success: function (data) {
               alert("Successfully Added")
            }
        });
    }
    
</script>
<script src="~/Content/CreateUser/js/createuser.js"></script>